### ISSUE TITLE
Radarcode sevar vs sevax

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#1]
For our flyway analyses we used the code [`sevar`](https://github.com/enram/vp-processing/blob/flyway/settings/radars.csv#L83) for the Swedish radar `Vara`. Data are uploaded to the ENRAM repository under that name: http://enram.github.io/data-repository/?prefix=se/var/

I noticed however that OPERA calls this radar [`sevax`](https://github.com/enram/dmp/blob/master/data/OPERA_RADARS_DB.json#L5415) (same radar coordinates) and that from 2017 onwards data are uploaded as such: http://enram.github.io/data-repository/?prefix=se/vax/

@CeciliaNilsson709 @leijnse which code is correct?

**Comment by CeciliaNilsson709** [comment]
They must have changes the name of it, completely sure it was **sevar** then. Maybe they changed it so the tre letter code doesn't overlap with bgvar? 🤷‍♀️

**Comment by peterdesmet** [comment]
Hmm, annoying. What do you think: should we should move the content from `sevar` to the `sevax` directory then, to indicate that it is the same radar? It will still remain `sevar` in the data package on Zenodo (which is good). It's unlikely OPERA will change it back for us.

**Comment by CeciliaNilsson709** [comment]
It was annoying that they weren't unique also though. I think it makes sense to move it, but maybe we should just double check that there is not something else going on first. I can look into it.

**Comment by peterdesmet** [comment]
VAR -> VAX is listed in https://github.com/enram/globam-dmp/issues/5#issuecomment-484941213, closing here.
