### ISSUE TITLE
add vp hdf5 data format specification to wiki

### ISSUE THREAD

**Issue by adokter** [enram/globam-dmp#12]
Available here: https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification

**Comment by peterdesmet** [comment]
Do you have documentation for the pvol hdf5 specification as well? The link in the wiki points to it, but it is broken: https://github.com/adokter/vol2bird/blob/master/documentation/OPERA2014-O4-ODIM-H5-v2.2.pdf

**Comment by adokter** [comment]
This is version 2.2
https://github.com/adokter/vol2bird/blob/master/doc/OPERA2014_O4_ODIM_H5-v2.2.pdf
Since a few months superseded by 2.3:
https://github.com/adokter/vol2bird/blob/master/doc/ODIM_H5_v23.pdf

**Comment by peterdesmet** [comment]
pvol format referenced at:

https://github.com/enram/globam-dmp/blob/a891e91613b0a7222ab5e890789fcf88dea08255/src/europe.Rmd#L80

vp format referenced at:

https://github.com/enram/globam-dmp/blob/a891e91613b0a7222ab5e890789fcf88dea08255/src/europe.Rmd#L132
