### ISSUE TITLE
Run latest version of vol2bird on baltrad

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#14]
Is baltrad running the latest vol2bird algorithm?

1. Download recent file: https://lw-enram.s3-eu-west-1.amazonaws.com/be/wid/2019/04/11/06/bewid_vp_20190411T064000Z_0x5.h5
2. Read with bioRad: 

```r
library(bioRad)
read_vpfiles("my_data/bewid_vp_20190411T062000Z_0x5.h5")
```

3. `generated by:  vol2bird 0.3.20`

That seems to be the [latest release](https://github.com/adokter/vol2bird/releases) @adokter?

**Comment by adokter** [comment]
Yes, that is the latest release on the master branch. A new release will be pushed soon.

**Comment by peterdesmet** [comment]
Ok, leaving issue open to not forget to update BALTRAD version once new release is created.

**Comment by adokter** [comment]
Sounds good. Would be nice to set up everything such that new versions can easily be pulled and deployed, as vol2bird will keep on evolving just like bioRad.

**Comment by peterdesmet** [comment]
From Slack:

> Günther said that it is only a small effort for him to install new versions and to get them working.

So nothing automated, but can be done rapidly still.
