### ISSUE TITLE
Define vpts tabular format

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#16]
Define which columns to include in a tabular format for vpts data (vertical profile time series). This file format will be used to generate monthly time series per radar, which are more convenient to use then individual hdf5 vp files. For discussion, see https://github.com/adokter/vol2bird/issues/120

**Comment by adokter** [comment]
see related issue https://github.com/adokter/bioRad/issues/66

**Comment by adokter** [comment]
see related issue https://github.com/adokter/vol2bird/issues/38, vol2bird has already some export functionality to JSON, which could be useful for exporting structured (meta)data in text format.

**Comment by peterdesmet** [comment]
🤔JSON would allow to combine data + metadata, but will be less straightforward than csv to concatenate into vpts. It can also be quite verbose. Not sure it's the best _storage_ format.

**Comment by peterdesmet** [comment]
Format is now defined at https://github.com/enram/vpts-csv
