### ISSUE TITLE
Document climate data in DMP

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#20]
"Climate data" was listed as an **external data source** we plan to use for GloBAM, which means we need to document it in our [DMP](https://github.com/enram/globam-dmp/blob/master/src/external_data.Rmd).

- What WP is going to use "climate data"?
- What source will be used for this data?
- Who can answer these questions? 🤷‍♂️

**Comment by CeciliaNilsson709** [comment]
I don't think anyone will be using "climate data" in the actual sense of the word, but that this will be the same data as [21](https://github.com/enram/globam-dmp/issues/21).

But I might be wrong?

**Comment by peterdesmet** [comment]
👍 I was already wondering about that. Will remove it from the dmp altogether.

**Comment by jshamoun** [comment]
This depends on whether or not we use climate forecasts for future scenarios.
Will be filled in once decided if this will one of the research questions
