### ISSUE TITLE
Document artificial light data in DMP

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#22]
"Artificial light data" was listed as an **external data source** we plan to use for GloBAM, which means we need to document it in our [DMP](https://github.com/enram/globam-dmp/blob/master/src/external_data.Rmd).

- What WP is going to use "artificial light data"?
- What source will be used for this data?
- Who can answer these questions? 🤷‍♂️

**Comment by CeciliaNilsson709** [comment]
We will use it in WP3, and we will use the VIIRS Day/Night band from NOAA:
https://ngdc.noaa.gov/eog/viirs/download_dnb_composites.html

We _might_ also use the new Black Marble product from NASA once it is released, but I think first hand it will be the VIIRS.

Is that enough for now? Can add details once we get started on the analysis?

**Comment by peterdesmet** [comment]
Awesome, that's great! Updated in DMP, should be online soon: https://enram.github.io/globam-dmp/external_data.html
