### ISSUE TITLE
Document wind energy installations data in DMP

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#23]
"Wind energy installations" was listed as an **external data source** we plan to use for GloBAM, which means we need to document it in our [DMP](https://github.com/enram/globam-dmp/blob/master/src/external_data.Rmd).

- What WP is going to use data on "wind energy installations"?
- What source will be used for this data?
- Who can answer these questions? 🤷‍♂️

**Comment by jshamoun** [comment]
*   What WP is going to use data on "wind energy installations"? Potentially WP4
  *   What source will be used for this data? Depends on the exact research questions and what’s available. Will fill in DMP once we know
  *   Who can answer these questions? 🤷‍♂️ Judy Shamoun-Baranes or whoever else is working on wind energy installations

**Comment by peterdesmet** [comment]
Thanks @jshamoun!
