### ISSUE TITLE
Define chapter on publications

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#29]
It hasn't been discussed yet, but the DMP should probably include a section on where we will publish papers and how open access these will be. Rmd should be called `8_publications.Rmd`.

**Comment by CeciliaNilsson709** [comment]
I don't think we should include too much on this: it will have to be a decision for each study what to aim for and then you never know where it ends up anyway. A open access plan and how (if) there are funds for it would be great though!

**Comment by peterdesmet** [comment]
Not included in the GloBAM DMP, but a list of publications is available at https://globam.science/publications
