### ISSUE TITLE
US pvol quality assurance

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#33]
@CeciliaNilsson709 @adokter how do you assess the quality of pvol files for the US (gaps in coverage, etc.)? Or is this done by NOAA?

https://github.com/enram/globam-dmp/blob/1b0019ae6f4c22baea7fa1fbbf710274d27484d9/src/3_pvol_us.Rmd#L65-L67

**Comment by CeciliaNilsson709** [comment]
Hmm, I don't think we really have a good answer to that, so far we have just done it on a study to study basis, depending on whether gaps would be an issue for a specific analysis etc.

**Comment by adokter** [comment]
The minimum interval at which radars provide data is approximately 10 minutes, so no files are present for 10 minutes or more I would identify that as a gap.

Also note that the interval at which radars acquire data may vary for individual radars, ranging from 4-10 minutes

The interval depends on the Volume Coverage Pattern (VCP), coded by an integer number, which is one of the important attributes to store, see https://en.wikipedia.org/wiki/NEXRAD#Scan_strategies

**Comment by peterdesmet** [comment]
Leaving as `unknown` in DMP. Closing issue.
