### ISSUE TITLE
Create figures to assess baltrad pvol coverage

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#34]
## All time figure

To have a better idea of the pvol data coverage in BALTRAD and compare radars over years, create heatmap figure with:

- rows: radars (164)
- columns: weeks (8 years * 52 = 416 and growing)
- values: colour gradient for % of expected data files (depends on sampling interval)

## Year figures

For more in depth inspection (but still ability to compare radars), create heatmap figure with:

- rows: radars (164)
- columns: days (366)
- values: colour gradient for % of expected data files (depends on sampling interval)

For both figures, we'll have to see if we should switch rows and columns. Figures could be created as RShiny and/or static.

**Comment by peterdesmet** [comment]
I'm not sure yet. I think it makes sense to include them in the DMP: chapter 2 already discusses Eureopean pvol data, it would make them available online, and then we don't have to setup something separately, but the dmp has limited interactivity, so it would be a lot of figures to show.

As the figures can be static, maybe we just need a script to generate them all and just place the figures in the repo and link to those?

**Comment by peterdesmet** [comment]
@CeciliaNilsson709 we could include each year figure as subsections somewhere in the DMP: the user would then be able to navigate through them with the arrow keys. 🤷‍♂️See https://inbo.github.io/steenuil_gooik/8-1-akker-of-tuinbouw.html for a working example.

**Comment by CeciliaNilsson709** [comment]
Sure, that could work. Making them into static figures will be easy. Is the file listing updated or is it just a static list from Günther?

**Comment by peterdesmet** [comment]
I'd say "fairly static": I only received the file listing once, but it's possible we'll receive updates in the future, which is why I documented the procedure in #15 and [baltrad_coverage.Rmd](https://github.com/enram/globam-dmp/blob/master/src/data/baltrad_summary.Rmd). I think the best option is to extend **that** file with the code to generate the figures. Figures can be placed in https://github.com/enram/globam-dmp/tree/master/images. We can name them `baltrad_pvol_2019.png`, `baltrad_pvol_be.png`, etc.

Let's focus on that first and figure out how to include them in the DMP later. The arrow keys has its disadvantages too, as it requires _each_ chapter to be broken up into separate html files.

**Comment by CeciliaNilsson709** [comment]
Ok, I can do that to start with 👌

**Comment by peterdesmet** [comment]
Suggested to combine BALTRAD pvol coverage with ENRAM vp coverage. And rather than showing colour gradient for % of expected data files, show a 3 categories:

- white: no pvol (and thus no vp data)
- orange: pvol available, but no vp
- blue: vp available (and thus also pvol)

I've create a dataframe `coverage` with this information:

https://github.com/enram/globam-dmp/blob/0352e8796f330aab9c242c4c5bdc5069d0ea48fe/src/data/baltrad_coverage.Rmd#L88-L94

**Comment by adokter** [comment]
Would it be possible to check the contents of the pvol, and indicate with separate colors the availability of VRAD and DBZH quantities?

**Comment by peterdesmet** [comment]
I’d like to, but we currently don’t have access to the files themselves, just he file names (52 million), which contain radar and datetime information.

I hope to read the files at a later stage and process them to vp, but that will require much more computing power and space. 😅

**Comment by peterdesmet** [comment]
Rmd to create figures are now included in separate directory: https://github.com/enram/globam-dmp/tree/master/baltrad
