### ISSUE TITLE
Switzerland (ch): no VP files 

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#36]
Switzerland has pvol files on BALTRAD, but vp files have never been created. @leijnse @adokter Any idea what the issue might be?

```
chalb
chdol
chlem
chppm
chwei
```

**Comment by adokter** [comment]
The problem used to be that Switzerland did not send radial velocity data. Can you check if the VRAD or VRADH quantity is present in these pvol files?

**Comment by baptischmi** [comment]
MeteoSwiss does only send cleaned data, i.e. precipitation only, and so meteoSwiss does for their archives. I am working on a solution to run vol2bird directly on their server and we should have a meeting before the end of the year.

**Comment by CeciliaNilsson709** [comment]
@baptisschmi, this would be great information to add to the google sheet ☺️👌

**Comment by adokter** [comment]
vp files are being generated on the ftp server. However, the profiles are empty, likely because, as @baptischmi mentioned, they are sending data in which biological data are removed

**Comment by peterdesmet** [comment]
Ok, now that we have the answer I will close this issue.
