### ISSUE TITLE
Spain (es): no longer generating vp files

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#39]
Spain has pvol files on BALTRAD, but vp files are no longer being created since 2019-07-12.

```
esalm
esbad
esbar
escor
eslid
eslpa: stopped since 2019-07-09 and more spotty
esmad
esmal
esmur
espma
essan
essev
essse
esval
eszar
```

@leijnse @adokter Any idea what the issue might be?

**Comment by peterdesmet** [comment]
Emailed Günther about this.

**Comment by adokter** [comment]
Profiles are available actually on baltrad ftp

**Comment by peterdesmet** [comment]
Great! 👏

**Comment by peterdesmet** [comment]
vp activated again for all radars except `esbar` en `eslpa`. Let's hope those kick in soon.
