### ISSUE TITLE
fikes: no longer generating vp files

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#40]
Finland has pvol files on BALTRAD, but vp files are no longer being created since 2018-02-12.

```
fianj
fiika
fikes
fikor
fikuo
filuo
fipet: stopped since 2017-11-01
fiuta
fivan
fivim
```

@leijnse @adokter Any idea what the issue might be?

**Comment by adokter** [comment]
I'm currently seeing vp files for these radars being generated at ftp://co-0181.c.ipeer.se, could this be an issue on your end downloading the vp files?

**Comment by leijnse** [comment]
No idea either.

**Comment by peterdesmet** [comment]
fikes vp data is available again since [2020-02-04](https://enram.github.io/data-repository/?prefix=fi/kes/2020/02/04/).

Gaps:
- 2018-02-12 → 2019-09-12
- 2019-11-25 → 2020-02-04

Closing issue
