### ISSUE TITLE
Norway (no): no VP files

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#42]
Norway has pvol files on BALTRAD, but vp files have never been created. @leijnse @adokter Any idea what the issue might be?

```
noand
nober
nobml
nohas
nohfj
nohgb
nohur
norsa
norst
nosmn
nosta
```

**Comment by adokter** [comment]
Norway is not sending radial velocity data, therefore no vp is being generated

**Comment by peterdesmet** [comment]
Ok, thanks!

**Comment by peterdesmet** [comment]
To verify before closing: https://github.com/enram/globam-dmp/issues/43#issuecomment-530456115

> One note of caution: the fact that radial velocity data is missing in the pvol can be a Baltrad issue with the merging. I would say for all countries with this issue it needs to be checked whether the data really are not being sent, or that they simply do not end up in the final pvol file.

**Comment by peterdesmet** [comment]
Norway **does** has additional files per timestamp, so I assume merging **is** going on. I currently don't have access to the files themselves, so I cannot check if the source files contain VRADH.

The hex codes in the additional files `0x1` and `0x8` but don't know yet how to translate them (see #35)

**Comment by leijnse** [comment]
I checked the internal OPERA site, and it says that Norway is delivering radial velocity to OPERA. I don't know why the profiles aren't generated on Baltrad. Reasons that I can think of are: 1) Norway is not delivering to OPERA; 2) VRADH are not transferred from OPERA to Baltrad; 3) VRADH for Norwegian data is not properly encoded; 4) Nyquist velocity is too low for all Norwegian data.

Any other suggestions for reasons? I can check this at the OPERA meeting in 1.5 weeks.

**Comment by peterdesmet** [comment]
@leijnse note:

1. Norway has plenty of pvol data on the BALTRAD archive and it is current (last checked date 2019-08-28):

```
radar	min_date	max_date
noand	2013-09-24	2019-08-28	 
nober	2013-10-29	2019-08-28	 
nobml	2013-09-24	2019-08-28	 
nohas	2013-09-24	2019-08-28	 
nohfj	2017-12-06	2019-08-27	 
nohgb	2013-09-24	2019-08-28	 
nohur	2013-09-24	2019-08-28	 
norsa	2013-09-24	2019-08-28	 
norst	2013-09-24	2019-08-28	 
nosmn	2015-05-12	2019-08-28	 
nosta	2013-09-24	2019-08-28
```

2. Files *are* being merged into single files per timestamp.

3. pvol files are available at the enram-accessible FTP server

4. vp files are not created.

**Comment by adokter** [comment]
> * Files _are_ being merged into single files per timestamp.
> 
> * Those single pvol files are available at the enram-accessible FTP server

But I don't think VRADH is available as a quantity in the pvol, so that leaves Hidde's option 1-3 as possibilities

**Comment by peterdesmet** [comment]
From 2020 onwards, vp data is available for Norway on BALTRAD and thus on the data repository: https://aloftdata.eu/browse/?prefix=baltrad/hdf5/noand/
