### ISSUE TITLE
United Kingdom (uk): no vp files

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#43]
United Kingdom has pvol files on BALTRAD, but vp files have never been created. @leijnse @adokter Any idea what the issue might be?

```
ukcas
ukche
ukcle
ukcob
ukcyg
ukdea
ukdud
ukham
ukhhd
ukhmy
uking
ukjer
uklew
ukmun
ukpre
ukthu
```

**Comment by adokter** [comment]
radial velocity data is missing in the pvol, therefore no vp is being generated.

**Comment by peterdesmet** [comment]
Ok, that answers the why. Closing issue.

**Comment by adokter** [comment]
> Ok, that answers the why. Closing issue.

One note of caution: the fact that radial velocity data is missing in the pvol can be a Baltrad issue with the merging. I would say for all countries with this issue it needs to be checked whether the data really are not being sent, or that they simply do not end up in the final pvol file.

**Comment by peterdesmet** [comment]
Question regarding the merging: it looks like I can detect merging is happening when there are multiple files for a single timestamp:

```
behel_pvol_20180226T125003Z.h5 -> contains merged data
behel_pvol_20180226T125003Z_0x1.h5
behel_pvol_20180226T125003Z_0x1_15196497864.h5
behel_pvol_20180226T125003Z_0x2.h5
behel_pvol_20180226T125003Z_0x2_151964975286.h5
```

Can I assume **no BALTRAD merging is happening if there is only a single file per timestamp?**

**Comment by peterdesmet** [comment]
The UK has no additional files per timestamp for any of the pvol files, so I assume no merging is going on. The missing radial velocity (VRADH) is therefore not a result of merging (i.e. an issue with BALTRAD), but an issue at the source.
