### ISSUE TITLE
behel: no vp files

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#44]
`behel` is submitting pvol data to BALTRAD since 2018, but vp data are not created and the radar code is not known in the [OPERA database](https://github.com/enram/globam-dmp/blob/master/data/OPERA_RADARS_DB.json).

@leijnse Is this a new code for `bezav` (which is in the OPERA database, but has no data on BALTRAD)?

Note that the processing functions as expected for:

```
bejab
bewid
```

**Comment by adokter** [comment]
This is the Helchteren radar, see https://www.cnc-nkc.be/sites/default/files/report/file/nc7_en_lr.pdf

**Comment by peterdesmet** [comment]
To verify before closing: https://github.com/enram/globam-dmp/issues/43#issuecomment-530456115

> One note of caution: the fact that radial velocity data is missing in the pvol can be a Baltrad issue with the merging. I would say for all countries with this issue it needs to be checked whether the data really are not being sent, or that they simply do not end up in the final pvol file.

**Comment by peterdesmet** [comment]
behel **does** have additional files per timestamp, so I assume merging **is** going on. I currently don't have access to the files themselves, so I cannot check if the source files contain VRADH.

The hex codes in the additional files are `0x1|0x2`, but I don't know yet how to translate them (see #35).

**Comment by leijnse** [comment]
The issue with the radar in Helchteren is that they don't use dual-PRF, which means that the velocity data is badly aliased, making it useless for vol2bird. So I wouldn't put too much effort into data from this radar.
