### ISSUE TITLE
Radar code bgvar, ctcdv, ctpda

### ISSUE THREAD

**Issue by peterdesmet** [enram/globam-dmp#6]
For our flyway analysis we have the radars:

- [`bgvar`](https://github.com/enram/vp-processing/blob/flyway/settings/radars.csv#L5): Bulgaria, Varna
- [`ctcdv`](https://github.com/enram/vp-processing/blob/flyway/settings/radars.csv#L6): Catalonia?
- [`ctpda`](https://github.com/enram/vp-processing/blob/flyway/settings/radars.csv#L7): Catalonia?

@CeciliaNilsson709 @leijnse These are [not listed by OPERA](https://github.com/enram/dmp/blob/master/data/OPERA_RADARS_DB.json), but I assume these are one-off datasets we got that are not necessarily part of OPERA? And that we likely won't get data from these radars through OPERA in the near future either?

If so, I will indicate them as such in the spreadsheet overview.

**Comment by CeciliaNilsson709** [comment]
Yes. We might still get more data from them, but yes.
