### ISSUE TITLE
Enlist polar volume (pvol) data currently stored by one of the partners

### ISSUE THREAD

**Issue by stijnvanhoey** [enram/globam-dmp#9]
For a limited set of countries and time periods, partners of the globam project already store pvol data at the moment. It is important to have an idea of what we would have available for the envisioned period 2016-2018 (3 years of data).

On [this gsheet](https://docs.google.com/spreadsheets/d/1dulZ4TLjxIjmUek5QP86uJ9DsZqm9d0G6vl6hnA0mw4/edit#gid=520083184), the third sheet `available pvol data` provides an overview of the existing radars. Please, provide as a __comment__ to the specific cell  the __number of days__ you have pvol data available. We prepared columns on a year basis (_2016 other partners_,....) for each radar (we'll compile the information based on these comments).

@jshamoun I do think uva in particular has some data stored, so some columns are already setup for you with write access ;-)

**Comment by stijnvanhoey** [comment]
@leijnse can you provide some information (comments in gsheet or here in comment) about the number of days with availability for each of the Dutch radars? A general estimate is good enough.

**Comment by peterdesmet** [comment]
This is being tackled in the spreadsheet. Closing issue.
